### ISSUE TITLE
what's the file model-8?

### ISSUE THREAD

**Issue by ervecherish** [jazzsaxmafia/show_attend_and_tell.tensorflow#1]
when I run train() in model_tensorflow.py, there would be a DataLossError: unable to find model-8.
so what's the model-8? a pre-trained model of tensorflow? How can i get it.

**Comment by jazzsaxmafia** [comment]
It is due to the line below.
https://github.com/jazzsaxmafia/show_attend_and_tell.tensorflow/blob/master/model_tensorflow.py#L227

You may set it to 
pretrained_model_path = None 
to fresh start training the model

**Comment by ervecherish** [comment]
thx, got it!
